### ISSUE TITLE
The “items” actions are not working on Apple devices. 

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#10]
Description: 
When the user click on some items that have configured actions, this does not work on apple devices.
 
-Env:
Crafter Gardeners Blueprint
Device: Iphone 6 plus 
 Ipad Pro  
Safari IOS 10.3
Google Chrome Version 55.0.2883.79
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Gardeners site.
2. On the “About Us” click the Icons.
3. Go to the “Our Works” section.
4. Click on the images to open the view.
 
CURRENT RESULT: 
==================== 
The “items” actions are not working on apple devices, in the case of the icons this should be highlighted when the user clicks on them and in the case of the images the application should open the view. 
 
EXPECTED RESULT: 
==================== 
The “items” actions should be working on apple devices.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 26c70a4.
