### ISSUE TITLE
The “Brands” logos are not displayed properly in mobile.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#11]
Description: 
The “Brands” logos are not displayed properly in mobile.
 
-Env:
Crafter Gardeners Blueprint
Device: Iphone 6 plus 
 Ipad Pro  
Safari IOS 10.3
Google Chrome Version 55.0.2883.79
 
Android 7.1
Google Chrome 55.0.2883.79
Firefox 54.0
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Gardeners site.
2. Go to the “Brands” section.
 
CURRENT RESULT: 
==================== 
The “Brands” logos are not displayed properly in mobile.
https://www.screencast.com/t/iuCS5SztjVCW 
 
EXPECTED RESULT: 
==================== 
The “Brands” logos are should be displayed properly in mobile.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build ee612e0.
