### ISSUE TITLE
The background videos are not displayed in some browsers.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#12]
Description:
When the user use mobile browsers the background video is not displayed.

Env.
Iphone 6 IOS 10.2
Iphone 7 IOS 10.3
Using:
Google Chrome 55.0.2883.79
Firefox 7.5(3349)
Safari

REPRODUCIBILITY LEVEL:
Always

STEPS:
1. Open the Gardeners site.
2. Go to the “Home” section.
3. Review the section.

CURRENT RESULT:
The application is not displaying the background video of the “Home” section in mobile browsers.

EXPECTED RESULT:
The application should display the background video of the “Home” section in mobile browsers.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Please test again using the most recent version of crafter

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in 64f19b0.
