### ISSUE TITLE
The site auto scroll (up or down)  when the “Our team” carrousel change of team member in mobile.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#15]
Description: 
When the “Our Team” carrousel change of team member with different properties, the page auto scroll (up or down) in the sections below. 
 
-Env:
Crafter Gardeners Blueprint
Device: Iphone 6 plus 
 Ipad Pro  
Safari IOS 10.3
Google Chrome Version 55.0.2883.79
 
Android 7.1
Google Chrome 55.0.2883.79
Firefox 54.0
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Gardeners site.
2. Go to the “Contact Us” section.
 
CURRENT RESULT: 
==================== 
The site auto scroll (up or down)  when the “Our team” carrousel change of team member in mobile.
https://www.screencast.com/t/T57qGZcne 
https://www.screencast.com/t/qeQ0hqsymE 
 
 
EXPECTED RESULT: 
==================== 
The site should not auto scroll (up or down)  when the “Our team” carrousel change of team member in mobile.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 64f19b0.
