### ISSUE TITLE
The application is redirecting to a non existing page, when the user clicks the “Lovely Patio” image.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#3]
Description: 
When the user click the “Lovely Patio” image, it is redirecting to a non existing page.
 
-Env:
Device: MacBook Pro 
Google Chrome Version 54.0.2840.98 (64-bit) 
Firefox 54.0 (64 Bit)
Safari Version 8.0.5 (10600.5.17) 
Internet Explorer 11.0.9600 

REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Gardeners site.
2. In the preview, go to the “Our Works” section.
3.  Click on the “Lovely Patio” image.
 
CURRENT RESULT: 
==================== 
The application redirects to a non existing page.
https://screencast.com/t/w1jU8jcFRW 
 
EXPECTED RESULT: 
==================== 
The application should redirects to a valid site or page section, or the site should display the image view.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build ee612e0.
