### ISSUE TITLE
The “Contact Us” button is not displayed properly in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#4]
Description: 
The “Contact Us” button is displayed completely attached to the section image. 
 
-Env:
Iphone 7 IOS 10.3 Safari
Android 7.1
Google Chrome 55.0.2883.79
Firefox 54.0
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Gardeners site.
2. In the preview, go to the “Our Business” section.
3. Review the “Contact Us” button.
 
CURRENT RESULT: 
==================== 
The “Contact Us” button is displayed completely attached to the section image. 
https://www.screencast.com/t/blA6tm9vm5f
https://www.screencast.com/t/1OxFLVOQ 
 
EXPECTED RESULT: 
==================== 
The “Contact Us” button should not be completely attached to the section image.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build ee612e0.

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build ee612e0.
