### ISSUE TITLE
The “Our Works” Image carrousel is not displayed properly in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#5]
Description: 
The “Our Works” Image carrousel is not displayed properly in mobile, the carrousel displays sometimes 3 images in arrow and sometimes only 1. 
 
 
-Env:
Crafter Hotel_Info Blueprint
Iphone 7 IOS 10.3 Safari
Android 7.1
Google Chrome 55.0.2883.79
Firefox 54.0
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Gardeners site.
2. In the preview, go to the “Our Works” section.
3. Review the images carrousel.
 
CURRENT RESULT: 
==================== 
The “Our Works” Image carrousel is not displayed properly in mobile, the carrousel displays sometimes 3 images in arrow and sometimes only 1. 
https://www.screencast.com/t/cbNjhR7a0ZVH 
 
EXPECTED RESULT: 
==================== 
The “Our Works” Image carrousel should be displayed properly in mobile, the carrousel should display only 1 image at the time.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 88133a5.
