### ISSUE TITLE
The application is displaying a non valid character, when the “Our Team” carrousel changes of team member.  

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#6]
Description: 
When the team member changes from one member to another an invalid character is displayed.
 
 
-Env:
Crafter Gardeners Blueprint
Device: Macbook Pro
Google Chrome Version 54.0.2840.98 (64-bit) 
Firefox Version 54.0 (64-bit) 
Safari Version 8.0.5 (10600.5.17)
 
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Gardeners site.
2. In the preview, go to the “Our Team” section.
3. Review the images carrousel.
 
CURRENT RESULT: 
==================== 
When the team member changes from one member to another an invalid character is displayed.(The characters are part of the text of the last image desplayed)
https://www.screencast.com/t/h2fmbBNSf 
https://www.screencast.com/t/lHdrLSJ5oGBz 
 
EXPECTED RESULT: 
==================== 
When the team member changes from one member to another non invalid character should be displayed.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build ee612e0.
