### ISSUE TITLE
The application allows to scroll in the site when an image of the “Our Works” carrousel is opened in mobile.

### ISSUE THREAD

**Issue by juacamar** [rivetlogic/craftercms-bp-gardeners#7]
Description:  
The application allows to scroll in the site when an image of the “Our Works” carrousel is opened in mobile.
 
-Env:
Crafter Gardeners Blueprint
Devices: 
Google Pixel, Android 7.1
Iphone 7 10.3
 
REPRODUCIBILITY LEVEL: 
==================== 
Always 
 
STEPS: 
==================== 
Steps 
1. Open the Crafter studio with the Gardeners site.
2. Go to the “Our Works” section and click on an image of the carrousel.
3. Scroll down and up the site.
 
CURRENT RESULT: 
==================== 
The application allows to scroll in the site when an image of the “Our Works” carrousel is opened.
https://www.screencast.com/t/NW9YDODbe9NQ 
 
EXPECTED RESULT: 
==================== 
The application should not allow to scroll in the site when an image of the “Our Works” carrousel is opened.

**Comment by LorenzoRodriguezRivetlogic** [comment]
Fixed

**Comment by juacamar** [comment]
Bug verified and closed as fixed in build 88133a5.
